name: native_socket
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.2
  native_assets_cli: ^0.7.2
  native_toolchain_c: ^0.5.2
  logging: ^1.2.0
dev_dependencies:
  ffigen: ^13.0.0
  lints: ^4.0.0
  test: ^1.25.8

ffigen:
  name: native_socket
  description: |

    Regenerate bindings with `flutter pub run ffigen --config ffigen.yaml`.
  output: "lib/src/native_socket.dart"
  headers:
    entry-points:
      - "src/native_socket.h"
    include-directives:
      - "src/native_socket.h"
  comments:
    style: any
    length: full
  ffi-native:
  llvm-path:
    - "/usr/lib/llvm"
    - "/usr/lib64/libclang.so"

  compiler-opts:
    - "-I/usr/lib/clang/18/include"
    - "-I/usr/local/include"
    - "-I/usr/include"
