// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:native_socket/native_socket.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int create_tmpfile_cloexec(ffi.Pointer<ffi.Char> tmpname);

@ffi.Native<ffi.Int Function(off_t)>()
external int os_create_anonymous_file(int size);

@ffi.Native<
  ssize_t Function(ffi.Int, ffi.Pointer<ffi.UnsignedChar>, ffi.Size)
>()
external int write_to_fd(
  int fd,
  ffi.Pointer<ffi.UnsignedChar> buffer,
  int count,
);

/// Create a socket of the given type (SOCK_STREAM or SOCK_DGRAM).
/// Returns fd on success, -1 on error. Socket is set NONBLOCK | CLOEXEC.
@ffi.Native<ffi.Int Function(ffi.Int)>()
external int create_socket(int type);

/// Bind a socket to a filesystem path.
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>)>()
external int bind_socket(int socket, ffi.Pointer<ffi.Char> path);

/// Bind a socket to an abstract namespace address.
/// The abstract name does NOT include the leading null byte (it's added by this function).
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>)>()
external int bind_socket_abstract(int socket, ffi.Pointer<ffi.Char> name);

/// Listen for incoming connections (stream sockets only).
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int listen_socket(int socket, int backlog);

/// Accept an incoming connection. Returns new fd on success, -1 on error.
@ffi.Native<ffi.Int Function(ffi.Int)>()
external int accept_socket(int socket);

@ffi.Native<ffi.Void Function(ffi.Int)>()
external void close_socket(int socket);

/// Unlink a socket path from the filesystem.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int unlink_socket_path(ffi.Pointer<ffi.Char> path);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int, ffi.Pointer<ffi.Int>)>()
external int get_socket_option(
  int socket,
  int level,
  int optname,
  ffi.Pointer<ffi.Int> value,
);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int)>()
external int set_socket_option(int socket, int level, int optname, int value);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int set_so_sndbuf(int socket, int size);

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int get_so_sndbuf(int socket);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int set_so_rcvbuf(int socket, int size);

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int get_so_rcvbuf(int socket);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int)>()
external int set_so_linger(int socket, int on_off, int linger_secs);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int create_unix_socket(ffi.Pointer<ffi.Char> path);

/// Connect a socket to a filesystem path.
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>)>()
external int connect_unix_socket(int socket, ffi.Pointer<ffi.Char> path);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Int>)>()
external int create_socketpair(ffi.Pointer<ffi.Int> sv);

/// Connect a socket to an abstract namespace address.
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>)>()
external int connect_unix_socket_abstract(
  int socket,
  ffi.Pointer<ffi.Char> name,
);

/// Send data to a specific address on a datagram socket.
/// Returns bytes sent or -1 on error.
@ffi.Native<
  ssize_t Function(
    ffi.Int,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>()
external int send_to(
  int socket,
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<ffi.Void> data,
  int data_len,
);

/// Send data to an abstract address on a datagram socket.
@ffi.Native<
  ssize_t Function(
    ffi.Int,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
  )
>()
external int send_to_abstract(
  int socket,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Void> data,
  int data_len,
);

/// Receive data from a datagram socket. Returns bytes received or -1.
/// The sender address is NOT returned (lower-level).
@ffi.Native<ssize_t Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size)>()
external int recv_from(int socket, ffi.Pointer<ffi.Void> buffer, int length);

@ffi.Native<ssize_t Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size)>()
external int send_bytes(int socket, ffi.Pointer<ffi.Void> buffer, int length);

@ffi.Native<
  ssize_t Function(ffi.Int, ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size)
>()
external int send_bytes_with_fd(
  int socket,
  int fd,
  ffi.Pointer<ffi.Void> data,
  int data_len,
);

@ffi.Native<ssize_t Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size)>()
external int recv_bytes(int socket, ffi.Pointer<ffi.Void> buffer, int length);

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int recv_fd(int socket);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<ffi.Int>,
    ffi.Int,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Size,
  )
>()
external ffi.Pointer<ffi.Void> unix_rights(
  ffi.Pointer<ffi.Int> fds,
  int num_fds,
  ffi.Pointer<ffi.UnsignedChar> buf,
  int buflen,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<cmsghdr>, ffi.Pointer<ffi.Int>, ffi.Int)
>()
external int parse_unix_rights(
  ffi.Pointer<cmsghdr> cm,
  ffi.Pointer<ffi.Int> fds,
  int max_fds,
);

@ffi.Native<ffi.Size Function(ffi.Size)>()
external int c_msg_len(int datalen);

@ffi.Native<ffi.Size Function(ffi.Size)>()
external int c_msg_space(int datalen);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int socket_has_data(int socket, int timeout);

typedef __off_t = ffi.Long;
typedef Dart__off_t = int;
typedef off_t = __off_t;
typedef __ssize_t = ffi.Long;
typedef Dart__ssize_t = int;
typedef ssize_t = __ssize_t;

final class cmsghdr extends ffi.Opaque {}
