name: Native Prebuilt Update Manifest
on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
      built-library-dir:
        required: false
        type: string
        default: built-library
      release-assets-dir:
        required: false
        type: string
        default: release-assets
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dart run native_prebuilt manifest update --config ${{ inputs.config }} --output lib/src/hook/asset_hashes.dart --built-library-dir ${{ inputs.built-library-dir }} --release-assets-dir ${{ inputs.release-assets-dir }}
